# Generated by Django 6.0.6 on 2026-06-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
    ]
